// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWt_cLLQiKgn_aGYrRmQS1qPXuslX1G4c',
    appId: '1:1092373893425:web:575b99e6b1ebf122466010',
    messagingSenderId: '1092373893425',
    projectId: 'tripmates-1a008',
    authDomain: 'tripmates-1a008.firebaseapp.com',
    storageBucket: 'tripmates-1a008.firebasestorage.app',
    measurementId: 'G-WNRFCTPX09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDl9qhiXBtkhYhc_PaYVtPSPdLxReCI0Y',
    appId: '1:1092373893425:android:c9d0e0b8e787b6b8466010',
    messagingSenderId: '1092373893425',
    projectId: 'tripmates-1a008',
    storageBucket: 'tripmates-1a008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCclY4s4wdmSo4iyC82VvCbOIkgXgIgeBY',
    appId: '1:1092373893425:ios:087fb7ec692c49ac466010',
    messagingSenderId: '1092373893425',
    projectId: 'tripmates-1a008',
    storageBucket: 'tripmates-1a008.firebasestorage.app',
    androidClientId: '1092373893425-1lit3e4o2i2rsiejsnm4c30s1nsdkfsl.apps.googleusercontent.com',
    iosClientId: '1092373893425-972su8on8uphlv5nm0l8p4ql6c0kdolg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripmates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCclY4s4wdmSo4iyC82VvCbOIkgXgIgeBY',
    appId: '1:1092373893425:ios:087fb7ec692c49ac466010',
    messagingSenderId: '1092373893425',
    projectId: 'tripmates-1a008',
    storageBucket: 'tripmates-1a008.firebasestorage.app',
    androidClientId: '1092373893425-1lit3e4o2i2rsiejsnm4c30s1nsdkfsl.apps.googleusercontent.com',
    iosClientId: '1092373893425-972su8on8uphlv5nm0l8p4ql6c0kdolg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripmates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWt_cLLQiKgn_aGYrRmQS1qPXuslX1G4c',
    appId: '1:1092373893425:web:035b1baeba022fe4466010',
    messagingSenderId: '1092373893425',
    projectId: 'tripmates-1a008',
    authDomain: 'tripmates-1a008.firebaseapp.com',
    storageBucket: 'tripmates-1a008.firebasestorage.app',
    measurementId: 'G-3PW9Y822KS',
  );
}
